<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tasks\**" />
    <EmbeddedResource Remove="Tasks\**" />
    <None Remove="Tasks\**" />
  </ItemGroup>

</Project>
