using KanBox.Domain.Abstractions;

namespace KanBox.Domain.Tests.Abstractions;

internal class EntityMock(Guid id) : Entity(id)
{
    public EntityMock() : this(Guid.Empty)  { }
}

[TestFixture]
public class EntityTest
{
    [Test]
    public void Constructor_NoProvidedId_ReturnsEntityWithAutogeneratedGuid()
    {

        Entity entity = new EntityMock();

        Assert.That(entity.Id, Is.Not.EqualTo(Guid.Empty));
    }
    
    [Test]
    public void Constructor_ProvidedId_ReturnsEntityWithExactGuid()
    {
        Guid expectedId = Guid.NewGuid();
        
        Entity entity = new EntityMock(expectedId);

        Assert.That(entity.Id, Is.EqualTo(expectedId));
    }
    
    [TestCaseSource(typeof(EntityExamples), nameof(EntityExamples.Equals_ProvidedSameOrDifferentGuids_ActualEqualToExpected_TestCases))]
    public void Equals_ProvidedSameOrDifferentGuids_ActualEqualToExpected(Guid firstId, Guid secondId, bool expected)
    {
        Entity firstEntity = new EntityMock(firstId);
        Entity secondEntity = new EntityMock(secondId);
        
        bool actual = firstEntity == secondEntity;
        
        Assert.That(actual, Is.EqualTo(expected));
    }
    
    [TestCaseSource(typeof(EntityExamples), nameof(EntityExamples.NotEquals_ProvidedSameOrDifferentGuids_ActualNotEqualToExpected_TestCases))]
    public void NotEquals_ProvidedSameOrDifferentGuids_ActualNotEqualToExpected(Guid firstId, Guid secondId, bool expected)
    {
        Entity firstEntity = new EntityMock(firstId);
        Entity secondEntity = new EntityMock(secondId);
        
        bool actual = firstEntity != secondEntity;
        
        Assert.That(actual, Is.EqualTo(expected));
    }
    
    [Test]
    public void Equals_ProvidedNullEntity_ReturnsFalse()
    {
        Entity entity = new EntityMock();
        Entity? nullEntity = null;
        
        bool actual = entity.Equals(nullEntity);
        Assert.That(actual, Is.False);
    }
}

public class EntityExamples
{
    public static IEnumerable<object[]> Equals_ProvidedSameOrDifferentGuids_ActualEqualToExpected_TestCases()
    {
        yield return [Guid.Parse("a805d4a0-8a77-4cae-b405-3254ec8fd92d"), Guid.Parse("a805d4a0-8a77-4cae-b405-3254ec8fd92d"), true ];
        yield return [Guid.NewGuid(), Guid.NewGuid(), false ];
        yield return [Guid.Empty, Guid.Empty, false];
    }
    
    public static IEnumerable<object[]> NotEquals_ProvidedSameOrDifferentGuids_ActualNotEqualToExpected_TestCases()
    {
        yield return [Guid.Parse("a805d4a0-8a77-4cae-b405-3254ec8fd92d"), Guid.Parse("a805d4a0-8a77-4cae-b405-3254ec8fd92d"), false ];
        yield return [Guid.NewGuid(), Guid.NewGuid(), true ];
        yield return [Guid.Empty, Guid.Empty, true];
    }
}